INSERT INTO awnsers (id, resposta, correta, pergunta_id, feedback, resposta_correta) VALUES
(1, 'É o exercício de listar as receitas e despesas do mês.', true, 1, NULL, NULL),
(2, 'Fazer compras a prazo.', false, 1, 'A questão fala sobre orçamento. É a ferramenta que permite que você planeje suas finanças. Ele retrata a sua situação financeira, ou seja, mostra quais são seus ganhos e gastos ao longo do mês.', 'É o exercício de listar as receitas e despesas do mês.'),
(3, 'Gerenciar dividas.', false, 1, 'A questão fala sobre orçamento. É a ferramenta que permite que você planeje suas finanças. Ele retrata a sua situação financeira, ou seja, mostra quais são seus ganhos e gastos ao longo do mês.', 'É o exercício de listar as receitas e despesas do mês.'),
(4, 'Fazer lista de compras.', false, 1, 'A questão fala sobre orçamento. É a ferramenta que permite que você planeje suas finanças. Ele retrata a sua situação financeira, ou seja, mostra quais são seus ganhos e gastos ao longo do mês.', 'É o exercício de listar as receitas e despesas do mês.'),
(5, 'Reduzir custo das compras realizadas.', false, 1, 'A questão fala sobre orçamento. É a ferramenta que permite que você planeje suas finanças. Ele retrata a sua situação financeira, ou seja, mostra quais são seus ganhos e gastos ao longo do mês.', 'É o exercício de listar as receitas e despesas do mês.'),
(6, 'É todo rendimento que compõe a renda mensal.', true, 2, NULL, NULL),
(7, 'São as despesas mensais.', false, 2, 'As receitas são todos os rendimentos que compõe sua renda mensal, como: salários, comissões, honorários, pró-labore, pensões, aposentadoria e rendimentos do trabalho informal ou autônomo.', 'É todo rendimento que compõe a renda mensal.'),
(8, 'São as compras realizadas durante o ano.', false, 2, 'As receitas são todos os rendimentos que compõe sua renda mensal, como: salários, comissões, honorários, pró-labore, pensões, aposentadoria e rendimentos do trabalho informal ou autônomo.', 'É todo rendimento que compõe a renda mensal.'),
(9, 'Significa comprar a prazo.', false, 2, 'As receitas são todos os rendimentos que compõe sua renda mensal, como: salários, comissões, honorários, pró-labore, pensões, aposentadoria e rendimentos do trabalho informal ou autônomo.', 'É todo rendimento que compõe a renda mensal.'),
(10, 'Compras no cartão de crédito.', false, 2, 'As receitas são todos os rendimentos que compõe sua renda mensal, como: salários, comissões, honorários, pró-labore, pensões, aposentadoria e rendimentos do trabalho informal ou autônomo.', 'É todo rendimento que compõe a renda mensal.'),
(11, 'Para fazer compras a prazo.', false, 3, 'A pergunta fala sobre orçamento. Visualizando suas receitas e suas despesas você verá no que estão seus maiores gastos e poderá fazer os ajustes necessários.', 'Para planejar os seus gastos.'),
(12, 'Para planejar os seus gastos.', true, 3, NULL, NULL),
(13, 'Para fazer compras no cartão de crédito.', false, 3, 'A pergunta fala sobre orçamento. Visualizando suas receitas e suas despesas você verá no que estão seus maiores gastos e poderá fazer os ajustes necessários.', 'Para planejar os seus gastos.'),
(14, 'Para pedir dinheiro emprestado.', false, 3, 'A pergunta fala sobre orçamento. Visualizando suas receitas e suas despesas você verá no que estão seus maiores gastos e poderá fazer os ajustes necessários.', 'Para planejar os seus gastos.'),
(15, 'Para fazer um crediário.', false, 3, 'A pergunta fala sobre orçamento. Visualizando suas receitas e suas despesas você verá no que estão seus maiores gastos e poderá fazer os ajustes necessários.', 'Para planejar os seus gastos.'),
(16, 'E o compromisso com valor igual que temos todos os meses.', true, 4, NULL, NULL),
(17, 'É comprar antecipadamente o que precisará no mês seguinte.', false, 4, 'As despesas fixas são os compromissos que você tem que pagar todos os meses, normalmente com valores iguais ou próximos, como o aluguel, prestação da casa, financiamento de veículo, mensalidade escolar etc.', 'É o compromisso com valor igual que temos todos os meses.'),
(18, 'É fazer investimentos no banco.', false, 4, 'As despesas fixas são os compromissos que você tem que pagar todos os meses, normalmente com valores iguais ou próximos, como o aluguel, prestação da casa, financiamento de veículo, mensalidade escolar etc.', 'E o compromisso com valor igual que temos todos os meses.'),
(19, 'É pagar as contas no crédito.', false, 4, 'As despesas fixas são os compromissos que você tem que pagar todos os meses, normalmente com valores iguais ou próximos, como o aluguel, prestação da casa, financiamento de veículo, mensalidade escolar etc.', 'É o compromisso com valor igual que temos todos os meses.'),
(20, 'É listar os custos da semana.', false, 4, 'As despesas fixas são os compromissos que você tem que pagar todos os meses, normalmente com valores iguais ou próximos, como o aluguel, prestação da casa, financiamento de veículo, mensalidade escolar etc.', 'É o compromisso com valor igual que temos todos os meses.'),
(21, 'são despesas que os valores sofrem alterações entre os meses.', true, 5, NULL, NULL),
(22, 'Comprar somente produtos recicláveis.', false, 5, 'As despesas variáveis são aquelas que sofrem alterações nos valores devido ao consumo, como a energia elétrica, água, telefone, gás, mercado, padaria, etc.', 'são despesas que os valores sofrem alterações entre os meses.'),
(23, 'Saber o valor exato dos ganhos.', false, 5, 'As despesas variáveis são aquelas que sofrem alterações nos valores devido ao consumo, como a energia elétrica, água, telefone, gás, mercado, padaria, etc.', 'são despesas que os valores sofrem alterações entre os meses.'),
(24, 'Fazer empréstimo no banco.', false, 5, 'As despesas variáveis são aquelas que sofrem alterações nos valores devido ao consumo, como a energia elétrica, água, telefone, gás, mercado, padaria, etc.', 'são despesas que os valores sofrem alterações entre os meses.'),
(25, 'Comprar em lojas diferentes.', false, 5, 'As despesas variáveis são aquelas que sofrem alterações nos valores devido ao consumo, como a energia elétrica, água, telefone, gás, mercado, padaria, etc.', 'são despesas que os valores sofrem alterações entre os meses.'),
(26, 'Uso antecipado dos recursos de bancos, lojas e etc.', true, 6, NULL, NULL),
(27, 'Usar os recursos do cartão de crédito.', false, 6, 'Crédito significa o uso de recursos de bancos, financeiras, lojas, entre outros, que possibilitam a antecipação do dinheiro para adquirir bens ou contratação de serviços. ', 'Uso antecipado dos recursos de bancos, lojas e etc.'),
(28, 'Ter o nome limpo.', false, 6, 'Crédito significa o uso de recursos de bancos, financeiras, lojas, entre outros, que possibilitam a antecipação do dinheiro para adquirir bens ou contratação de serviços. ', 'Uso antecipado dos recursos de bancos, lojas e etc.'),
(29, 'Empréstimo de dinheiro.', false, 6, 'Crédito significa o uso de recursos de bancos, financeiras, lojas, entre outros, que possibilitam a antecipação do dinheiro para adquirir bens ou contratação de serviços.', 'Uso antecipado dos recursos de bancos, lojas e etc.'),
(30, 'Fazer empréstimo.', false, 6, 'Crédito significa o uso de recursos de bancos, financeiras, lojas, entre outros, que possibilitam a antecipação do dinheiro para adquirir bens ou contratação de serviços. ', 'Uso antecipado dos recursos de bancos, lojas e etc.'),
(31, 'Cartão de crédito.', false, 7, 'Exemplos de créditos são: compra a prazo, empréstimo pessoal, financiamento, uso do cheque especial, cartão de crédito e crédito consignado.\r\n\r\n', 'Compra no débito.'),
(32, 'Compra a prazo.', false, 7, 'Exemplos de créditos são: compra a prazo, empréstimo pessoal, financiamento, uso do cheque especial, cartão de crédito e crédito consignado.\r\n\r\n', 'Compra no débito.'),
(33, 'Cheque especial', false, 7, 'Exemplos de créditos são: compra a prazo, empréstimo pessoal, financiamento, uso do cheque especial, cartão de crédito e crédito consignado.\r\n\r\n', 'Compra no débito.'),
(34, 'Compra no débito.', true, 7, NULL, NULL),
(35, 'Empréstimo pessoal.', false, 7, 'Exemplos de créditos são: compra a prazo, empréstimo pessoal, financiamento, uso do cheque especial, cartão de crédito e crédito consignado.\r\n\r\n', 'Compra no débito.'),
(36, 'Porcentagem que vem na fatura.', false, 8, 'Quem empresta sempre cobra um valor adicional pela antecipação do dinheiro. Esse valor adicional é chamado de juros. Assim, sempre que utilizamos um crédito, pagamos mais caro pelo produto ou serviço, por causa dos juros.', 'A cobrança de um valor adicional pela antecipação do dinheiro.'),
(37, 'A cobrança de um valor adicional pela antecipação do dinheiro.', true, 8, NULL, NULL),
(38, 'Valor cobrado quando atrasa a fatura.', false, 8, 'Quem empresta sempre cobra um valor adicional pela antecipação do dinheiro. Esse valor adicional é chamado de juros. Assim, sempre que utilizamos um crédito, pagamos mais caro pelo produto ou serviço, por causa dos juros.', 'A cobrança de um valor adicional pela antecipação do dinheiro.'),
(39, 'Valor cobrado anualmente.', false, 8, 'Quem empresta sempre cobra um valor adicional pela antecipação do dinheiro. Esse valor adicional é chamado de juros. Assim, sempre que utilizamos um crédito, pagamos mais caro pelo produto ou serviço, por causa dos juros.', 'A cobrança de um valor adicional pela antecipação do dinheiro.'),
(40, 'Valor que se paga todo mês.', false, 8, 'Quem empresta sempre cobra um valor adicional pela antecipação do dinheiro. Esse valor adicional é chamado de juros. Assim, sempre que utilizamos um crédito, pagamos mais caro pelo produto ou serviço, por causa dos juros.', 'A cobrança de um valor adicional pela antecipação do dinheiro.'),
(41, 'Sim.', true, 9, NULL, NULL),
(42, 'Não.', false, 9, 'Quando compramos um produto com pagamento parcelado, não precisamos pagar o valor total no momento da compra, mas ficamos com uma dívida. Assumimos o dever de pagar, no futuro, as parcelas restantes, por isso estamos fazendo uso de um crédito. ', 'Sim.'),
(43, 'Por que não precisamos pagar o valor total no momento da compra.', true, 10, NULL, NULL),
(44, 'Por que pagamos juros em todas as parcelas mensais.', false, 10, 'Quando compramos um produto com pagamento parcelado, não precisamos pagar o valor total no momento da compra, mas ficamos com uma dívida. Assumimos o dever de pagar, no futuro, as parcelas restantes, por isso estamos fazendo uso de um crédito. ', 'Por que não precisamos pagar o valor total no momento da compra.'),
(45, 'Por que estamos emprestando daquele estabelecimento.', false, 10, 'Quando compramos um produto com pagamento parcelado, não precisamos pagar o valor total no momento da compra, mas ficamos com uma dívida. Assumimos o dever de pagar, no futuro, as parcelas restantes, por isso estamos fazendo uso de um crédito. ', 'Por que não precisamos pagar o valor total no momento da compra.'),
(46, 'Por que vamos ficar devendo.', false, 10, 'Quando compramos um produto com pagamento parcelado, não precisamos pagar o valor total no momento da compra, mas ficamos com uma dívida. Assumimos o dever de pagar, no futuro, as parcelas restantes, por isso estamos fazendo uso de um crédito. \r\n\r\n', 'Por que não precisamos pagar o valor total no momento da compra.'),
(47, 'Por que o valor do produto dobra nesse tipo de compra.', false, 10, 'Quando compramos um produto com pagamento parcelado, não precisamos pagar o valor total no momento da compra, mas ficamos com uma dívida. Assumimos o dever de pagar, no futuro, as parcelas restantes, por isso estamos fazendo uso de um crédito. \r\n\r\n', 'Por que não precisamos pagar o valor total no momento da compra.');


INSERT INTO questions (pergunta, fase) VALUES
('O que é orçamento mensal?', 1),
('O que é receita?', 1),
('Por que fazer um orçamento? ', 1),
('O que é despesa fixa? ', 1),
('O que é despesa variável? ', 1),
('Crédito é :', 2),
('Abaixo assinale o que não é considerado crédito:', 2),
('O que é juros?', 2),
('Quando fazemos compras a prazo, estamos usando o crédito?', 2),
('Porque?', 2);

/*=== FOREING KEY === */
ALTER TABLE points ADD CONSTRAINT fk_points FOREIGN KEY (user_id) REFERENCES users ( id ) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE accounts ADD CONSTRAINT fk_accounts FOREIGN KEY (user_id) REFERENCES users ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
